public with sharing class Constants {
    public static final String CONTENT_TYPE_PDF = 'application/pdf';
    public static final String S3_ENDPOINT = 'callout:AWS_S3/';
    public static final String STATUS_SENT = 'Sent';
    public static final String STATUS_PAID = 'Paid';
    public static final String INVOICE_FILE_NAME_PREFIX = 'Invoice_';
    public static final String FILE_EXTENSION_PDF = '.pdf';
    public static final String SHARE_TYPE_VIEW = 'V';
    public static final String VISIBILITY_ALL_USERS = 'AllUsers';
    public static final String S3_ERROR_MESSAGE = 'Could not upload attachment to S3.';
}